function [Y] = startingpoint_value( p , inputs )
%STARTING POINT compute the concentrations of mrna and proteins after a
%night for =/= inducer concentrations. the format of the inducer is
%[ATC;IPTG] it should contain only 1 value for each inducer.

    Y(3)=0; %LacI
    Y(4)=0; %TetR
    
    Y(1) = (p.km0l ...
            + p.kml * hill_func(    Y(4) * hill_func(    inputs(1), ...
                                                         p.thetaaTc, ...
                                                         p.etaaTc), ...
                                    p.thetatetr, p.etaTetR) )./p.gml;
    Y(2) = (p.km0t ...
            + p.kmt * hill_func(    Y(3) * hill_func(    inputs(2), ... 
                                                         p.thetaIPTG, ...
                                                         p.etaIPTG), ...
                                    p.thetalaci, p.etaLacI) )./p.gmt;
        
   
    Y(5)= inputs(2);
    Y(6)= inputs(1);
end
